//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace SbisParser.FileNds {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Файл {
        
        private ФайлДокумент документField;
        
        private string идФайлField;
        
        private string версПрогField;
        
        private decimal версФормField;
        
        /// <remarks/>
        public ФайлДокумент Документ {
            get {
                return this.документField;
            }
            set {
                this.документField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл {
            get {
                return this.идФайлField;
            }
            set {
                this.идФайлField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог {
            get {
                return this.версПрогField;
            }
            set {
                this.версПрогField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ВерсФорм {
            get {
                return this.версФормField;
            }
            set {
                this.версФормField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокумент {
        
        private ФайлДокументКнигаПокуп книгаПокупField;
        
        private byte индексField;
        
        private byte номКоррField;
        
        private byte признСвед8Field;
        
        /// <remarks/>
        public ФайлДокументКнигаПокуп КнигаПокуп {
            get {
                return this.книгаПокупField;
            }
            set {
                this.книгаПокупField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Индекс {
            get {
                return this.индексField;
            }
            set {
                this.индексField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte НомКорр {
            get {
                return this.номКоррField;
            }
            set {
                this.номКоррField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte ПризнСвед8 {
            get {
                return this.признСвед8Field;
            }
            set {
                this.признСвед8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументКнигаПокуп {
        
        private ФайлДокументКнигаПокупКнПокСтр[] кнПокСтрField;
        
        private decimal сумНДСВсКПкField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КнПокСтр")]
        public ФайлДокументКнигаПокупКнПокСтр[] КнПокСтр {
            get {
                return this.кнПокСтрField;
            }
            set {
                this.кнПокСтрField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумНДСВсКПк {
            get {
                return this.сумНДСВсКПкField;
            }
            set {
                this.сумНДСВсКПкField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументКнигаПокупКнПокСтр {
        
        private byte кодВидОперField;
        
        private string датаУчТовField;
        
        private ФайлДокументКнигаПокупКнПокСтрСвПрод свПродField;
        
        private ushort номерПорField;
        
        private string номСчФПродField;
        
        private string датаСчФПродField;
        
        private decimal стоимПокупВField;
        
        private decimal сумНДСВычField;
        
        /// <remarks/>
        public byte КодВидОпер {
            get {
                return this.кодВидОперField;
            }
            set {
                this.кодВидОперField = value;
            }
        }
        
        /// <remarks/>
        public string ДатаУчТов {
            get {
                return this.датаУчТовField;
            }
            set {
                this.датаУчТовField = value;
            }
        }
        
        /// <remarks/>
        public ФайлДокументКнигаПокупКнПокСтрСвПрод СвПрод {
            get {
                return this.свПродField;
            }
            set {
                this.свПродField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort НомерПор {
            get {
                return this.номерПорField;
            }
            set {
                this.номерПорField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомСчФПрод {
            get {
                return this.номСчФПродField;
            }
            set {
                this.номСчФПродField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаСчФПрод {
            get {
                return this.датаСчФПродField;
            }
            set {
                this.датаСчФПродField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтоимПокупВ {
            get {
                return this.стоимПокупВField;
            }
            set {
                this.стоимПокупВField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумНДСВыч {
            get {
                return this.сумНДСВычField;
            }
            set {
                this.сумНДСВычField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументКнигаПокупКнПокСтрСвПрод {
        
        private ФайлДокументКнигаПокупКнПокСтрСвПродСведЮЛ сведЮЛField;
        
        /// <remarks/>
        public ФайлДокументКнигаПокупКнПокСтрСвПродСведЮЛ СведЮЛ {
            get {
                return this.сведЮЛField;
            }
            set {
                this.сведЮЛField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументКнигаПокупКнПокСтрСвПродСведЮЛ {
        
        private ulong иННЮЛField;
        
        private uint кППField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong ИННЮЛ {
            get {
                return this.иННЮЛField;
            }
            set {
                this.иННЮЛField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint КПП {
            get {
                return this.кППField;
            }
            set {
                this.кППField = value;
            }
        }
    }
}
